Repository openshift/machine-api-provider-openstack, pull requests merged in 2021-12, with the labels that each got.

#14 mod: Run go mod tidy && go mod vendor
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/identity_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackcluster_conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackcluster_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackcluster_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackclusterlist_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackclustertemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackclustertemplate_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackmachine_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackmachine_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackmachinelist_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackmachinetemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackmachinetemplate_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/openstackmachinetemplatelist_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/webhooks.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/cluster_phase_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/cluster_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/clusterclass_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/common_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/condition_consts.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/condition_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/conversion.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/doc.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machine_phase_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machine_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machinedeployment_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machinehealthcheck_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machineset_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/zz_generated.deepcopy.go
Labels: lgtm, approved

#16 Bug 2033382: Fix missing machine annotations
  pkg/machine/actuator.go
  pkg/machine/machineScript.go
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high

#18 Bug 2034534: Run `go fmt ./...`
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: bugzilla/severity-medium, lgtm, bugzilla/valid-bug, approved

#19 Bug 2034537: OWNERS: Update team members
  OWNERS_ALIASES
Labels: bugzilla/severity-medium, lgtm, bugzilla/valid-bug, approved
