Repository openshift/machine-api-provider-openstack, pull requests merged in 2023-11, with the labels that each got.

#93 OSASINFRA-3283: convert: add missing port profile
  pkg/machine/convert.go
Labels: lgtm, approved, jira/valid-reference

#94 NO-JIRA: Misc linter fixes
  pkg/machine/actuator.go
  pkg/machine/convert.go
Labels: lgtm, approved, jira/valid-reference

#90 OCPBUGS-16597: Don't build InstanceSpec during delete operations
  pkg/machine/actuator.go
  pkg/machine/convert.go
  pkg/machine/convert_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#96 OSASINFRA-3297: Remove unnecessary retrieval of Network ID
  pkg/machine/convert.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#98 OCPBUGS-23913: Fix nil pointer exception when deleting machines without a root volume
  pkg/machine/actuator.go
  pkg/machine/convert.go
  pkg/machine/convert_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#97 OCPBUGS-23668: Bump Kubernetes dependencies
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
