Repository openshift/machine-api-provider-openstack, pull requests merged in 2024-05, with the labels that each got.

#112 OCPBUGS-33954: Failure to get bootstrap is non-fatal
  pkg/machine/actuator.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#113 NO-JIRA: Remove a stray comment
  pkg/machine/convert.go
Labels: lgtm, approved, jira/valid-reference

#118 NO-JIRA: Update shiftstack-team in OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
